#cloud-config

# update cloud-config without reboot
# sudo coreos-cloudinit --from-file=/var/lib/coreos-install/user_data

# include one or more SSH public keys
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDIfjbJVyHtkv/J6sSieaOnAybVLM1M6iwTRcWoyg2o8WakW4ZKee+Ss+SbEaMBPb4pNYNnU+TNd2U4eWvwhJ/vZkQK/6Cv5mC9SdSwN/6I5HUsWoEHW1YmMwRiZUtBblA5YC3kEAZra9CeaZdhAsvhA5rT7K1hOOq2VeaAp2ZgQbT/uSg7rrFfLoELvKWHzCWAoSqXiVQZ//35QX9LI212vPpsAqBj8OQLFQu1AeDgfpad5rmdtADsFOu/0vpLWjQ4553ha7Er+8fqh9q/UUCDdIqHaYrJgNFWyCiQiFQWRN0GaxxjZJSAFT+VGfQUjTqo6FF7lM7nU+d9ziUyu8D"

hostname: "coreos"

coreos:  
  units:
    - name: 00-enp15s0.network
      runtime: true
      content: |
        [Match]
        Name=enp15s0
        [Network]
        DNS=8.8.8.8
        Address=192.168.3.130/24
        Gateway=192.168.3.1

    # Eth interface 1 - ip 120 range
    - name: 20-multi_ip.network
      content: |
        [Unit]
        Description= Setup multi_ip for 2 network interfaces (ip 120 & 130 range)

        [Match]
        Name=enp14s0
        [Network]
        DNS=8.8.8.8
        Address=192.168.3.120/24
        Gateway=192.168.3.1
        Address=192.168.3.121/24
        Gateway=192.168.3.1
        Address=192.168.3.122/24
        Gateway=192.168.3.1
        Address=192.168.3.123/24
        Gateway=192.168.3.1

    #- name: 30-multi_ip.network
    #  content: |
    #    [Unit]
    #    Description= Setup multi_ip for 2 network interfaces (ip 120 & 130 range)
    #    [Match]
    #    Name=enp15s0
    #    [Network]
    #    DNS=8.8.8.8
    #    Address=192.168.3.131/24
    #    Gateway=192.168.3.1
    #    Address=192.168.3.132/24
    #    Gateway=192.168.3.1

    # mount unit name has to follow mount destination path
    # Storage Main
    - name: mnt-storage.mount
      command: start
      content: |
        [Unit]
        Description= Primary storage Drive

        [Mount]
        What=/dev/disk/by-uuid/8a65b7df-0598-4cf1-ab71-10394c0f18ce
        Where=/mnt/storage
        Type=ext4

    # Storage Backup
    - name: mnt-storage_bak.mount
      command: start
      content: |
        [Unit]
        Description= Backup storage Drive

        [Mount]
        What=/dev/disk/by-uuid/55b3fa50-41f0-4f05-bbe4-47cb5965079a
        Where=/mnt/storage_bak
        Type=ext4

    # Other
    - name: mnt-other.mount
      command: start
      content: |
        [Unit]
        Description= Addition storage Drive

        [Mount]
        What=/dev/disk/by-uuid/e7ff45e3-4932-4eab-9193-4e50478a7b72
        Where=/mnt/other
        Type=ext4


    #- name: docker-tcp.socket
    #  command: start
    #  content: |
    #    [Unit]
    #    Description= ssh port to specific ip

    #   [Socket]
    #    ListenStream=192.168.3.120:22
    #    FreeBind=true

    #- name: runcmd.service
    #  command: start
    #  content: |
    #    [Unit]
    #    Description= Create virutal network interface

    #    [Service]
    #    Type=oneshot
    #    ExecStart=/bin/sh -c "ifconfig enp14s0:0 192.168.3.121 && \
    #                          ifconfig enp14s0:1 192.168.3.122 && \
    #                          ifconfig enp14s0:2 192.168.3.123"
